### ISSUE TITLE
Dates deleting themselves

### ISSUE THREAD

**Issue by zcrysler** [MotusWTS/Motus-TO-DO#68] opened 2017-09-12 18:45 UTC
Related to the last issue, I was fixing an existing terminated deployment, and deleted an antenna.  When I saved it deleted the start and end dates that were previously in the system.  Dates are usually non-editable once an end date has been entered.

**Comment by zcrysler** [comment] 2017-09-12 18:49
I think this is an issue with "save changes and close", it keeps deleting dates whenever I click this.  Seems like in order to make any changes and keep dates saved, you have to "save" and then use the back button to go back to the receivers page, then refresh to make sure it saved.

**Comment by Hussell** [comment] 2017-09-14 13:24
Duplicate of #67, I think (same root cause).

**Closed** 2017-09-14 13:25 UTC
Labels: bug, duplicate
